apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  MONGO_INITDB_ROOT_USERNAME: pineapple
  MONGO_INITDB_ROOT_PASSWORD: aWU8ztWJpMUakEscOLItkXYzhKnXdvqRknbIzqUymFNew0ZACmfhbR3XhJxdxtl65rKv3EjgAIerACDbOq7oAA==